apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secretless-demo.fullname" . }}
  labels:
    app: {{ include "secretless-demo.name" . }}
    chart: {{ include "secretless-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  secretless.yml: |
    listeners:
      - name: pg
        protocol: pg
        address: localhost:5432

    handlers:
      - name: pg
        listener: pg
        debug: true
        credentials:
          - name: address
            provider: kubernetes
            id: {{ include "secretless-demo.fullname" . }}-credentials#address
          - name: username
            provider: kubernetes
            id: {{ include "secretless-demo.fullname" . }}-credentials#username
          - name: password
            provider: kubernetes
            id: {{ include "secretless-demo.fullname" . }}-credentials#password
